### ISSUE TITLE
Request: update Stylelint version

### ISSUE THREAD

**Issue by efueger** [gilbarbara/codeclimate-stylelint#40]
Emily here from Code Climate Support. 
- We've had an oss customer hitting unknown rule errors like "Error: Undefined rule scss/at-each-key-value-single-line" 
- see more builds here: https://codeclimate.com/github/Dark-Heresy/front-end/builds

With other plugins, this typically is a versioning issue.

@gilbarbara - what do you think? Do you think updating the plugin would help with this?

Let me know if I can provide additional details. Happy to help.

Thanks!

**Comment by miktirr** [comment]
Upgrading to [the latest stylelint version (13.7.x)](https://github.com/stylelint/stylelint/releases/tag/13.7.0) and configuration practices seems to break this engine.

This is because stylelint has deprecated `*-blacklist`, `*-requirelist` and `*-whitelist` rules in favor of the new `*-disallowed-list`, `*-required-list` and `*-allowed-list` ones.

If one migrates to the new rule names, this engine fails and throws error related to the new naming conventions:

<img width="1079" alt="Screen Shot 2020-09-07 at 13 22 02" src="https://user-images.githubusercontent.com/6806359/92377809-6899cc00-f10d-11ea-9bd0-ea4aa7db9547.png">

**Comment by efueger** [comment]
Thanks for the report @miktirr .
- can you send me a link to the error page above? or to your repo?

Cheers,
Emily

**Comment by miktirr** [comment]
Sure, @efueger! The repo itself is not public but you should see the build error here: https://codeclimate.com/repos/5da99cdb529bf4014e0092bb/builds/2165 I’m also happy to provide additional details of our setup, if it helps.

**Comment by gilbarbara** [comment]
hey @efueger 
You need to update the engine. It is running a really old version.

Anyway, it has been updated in 2.3.0 (engine 13.7.2)
